# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$timein $directory$all'
right_format = """$status"""
add_newline = false

# A continuation prompt that displays two filled in arrows
continuation_prompt = "[âœâœâœ](bold green) "

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

[status]
symbol = 'ğŸ”´ '
format = '[$symbol$int\[$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[hostname]
ssh_only = false
ssh_symbol = 'ğŸŒ '
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = true

[docker_context]
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[git_metrics]
disabled = false

[time]
disabled = false

[line_break]
disabled = true
